general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 6000  # 60 min inactivity lock
    on-timeout = hyprlock
}

listener {
    event = "lid closed"
    on-event = hyprlock
}
