return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs", -- Sets main module to use for opts
	opts = {
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true, disable = { "dart" } },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<bs>",
			},
		},

		ensure_installed = {
			"go",
			"terraform",
			"lua",
			"python",
			"rust",
			"regex",
			"json",
			"javascript",
			"typescript",
			"tsx",
			"html",
			"css",
			"scss",
			"prisma",
			"markdown",
			"markdown_inline",
			"svelte",
			"vue",
			"graphql",
			"bash",
			"vim",
			"vimdoc",
			"dockerfile",
			"gitignore",
			"groovy",
			"toml",
			"yaml",
			"make",
			"cmake",
			"c",
			"c_sharp",
			"java",
			"http",
			"sql",
			"query",
			"astro",
			"svelte",
		},
	},
}
