console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
auto_upgrade = true
final_space = true

[palette]
  blue = '#2B5999'
  error = '#C21E56'
  green = '#166852'
  grey = '#666666'
  orange = '#ff645b'
  text-black = '#212121'
  text-blue-100 = '#eaeef5'
  text-green-100 = '#e8f0ee'
  text-orange-100 = '#ffeeed'
  text-white = '#FAFAFA'
  white = '#FAFAFA'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Path }} '
    foreground = 'p:text-orange-100'
    background = 'p:orange'
    type = 'path'

    [blocks.segments.properties]
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:text-blue-100'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'git'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:blue{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}p:green{{ end }}', '{{ if gt .Behind 0 }}p:error{{ end }}']

    [blocks.segments.properties]
      branch_icon = '  '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#689f63'
    type = 'node'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#00acd7'
    type = 'go'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4063D8'
    type = 'julia'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#FFDE57'
    type = 'python'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']
    invert_powerline = true

    [blocks.segments.properties]
      display_default = false

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'powerline'
    template = '  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#ffff66'
    type = 'root'
    invert_powerline = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .FormattedMs }}  '
    foreground = 'p:text-white'
    powerline_symbol = ''
    background = 'p:grey'
    type = 'executiontime'
    invert_powerline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '
    foreground = 'p:text-green-100'
    background = 'p:green'
    type = 'status'
    background_templates = ['{{ if gt .Code 0 }}p:error{{ end }}']
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = 'p:text-white'
    background = 'p:grey'
    type = 'time'
    invert_powerline = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '╰─'
    foreground = 'p:orange'
    type = 'text'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    style = 'plain'
    foreground = '#d3d7cf'
    type = 'text'

